### ISSUE TITLE
Figure out how to implement custom map tiles

### ISSUE THREAD

**Issue by Bialogs** [KittenSoftware/Catmaps#3]
Research how to implement custom map tiles in order to use the open source maps. Important to note limitations of older devices. Be sure to create a new wiki page including your findings so we don't forget. 

Things to consider:
- How they need to be stored in the app package as they will not be downloaded from a server
- Limits on size/ RAM limitations on devices
- Ways to call the images into the program

**Comment by PashoArerreug** [comment]
Thanks, Kyle!

**Comment by Bialogs** [comment]
Welcome. Don't do econ.

**Comment by PashoArerreug** [comment]
I'm not doing econ, not in econ. This was your idea.

**Comment by Bialogs** [comment]
Appreciated.

**Comment by Bialogs** [comment]
I love lamp
